# Generated by Django 5.1.1 on 2024-11-02 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebikes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='start_date',
        ),
        migrations.AddField(
            model_name='report',
            name='rental',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ebikes.rental'),
        ),
        migrations.AlterField(
            model_name='report',
            name='generated_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='ebikes.vehicle'),
        ),
    ]
