# Generated by Django 5.1 on 2024-11-04 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ebikes', '0002_remove_report_end_date_remove_report_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chargingpoint',
            old_name='charging_location',
            new_name='location',
        ),
    ]
