# Generated by Django 5.1.1 on 2024-11-06 14:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebikes', '0004_profile_alter_rental_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
